### ISSUE TITLE
Does it allow separate access control for Appmode and NB mode ?

### ISSUE THREAD

**Issue by LostQuant** [oschuett/appmode#21]
Just find this repo, wonder if this Appmode allows separate access control (i.e. using a different password from NBmode to access the appmode) ?  If not, is it possible to do so ? If so, I am happy to contribute if necessary.

**Comment by oschuett** [comment]
Well, I guess you could setup some proxy which treads appmode urls differently than notebook urls. 
However, Appmode only hides some of the UX elements. So, from a security point of view there is no difference between Appmode and NBmode.

I also don't think this could be added, because Jupyter is by design very open. If you want to build something secure you should either sandbox the whole Jupyter server or use a different technology.
