### ISSUE TITLE
Use the JupyterLab output area

### ISSUE THREAD

**Issue by jasongrout** [oschuett/appmode#3]
Rather than basing this on the classic notebook and hiding what we don't want, we could use the new JupyterLab output area component to make essentially a new notebook renderer, that has exactly just the things that we want (i.e., no code cells, etc.).

Basically, we could implement a *very* simple notebook renderer along the lines of the [web3](https://github.com/jupyter-widgets/ipywidgets/tree/master/examples/web3) example in the ipywidgets repo, which reads in a notebook, executes all cells, but only display the output of cells (or markdown cells) with a certain metadata tag. This lets you have a larger notebook with debugging stuff, stuff explaining the code, etc., but the 'app mode' is confined to specially-marked cells.

**Comment by oschuett** [comment]
Hi Jason, sorry for the late reply. 

> we could use the new JupyterLab output area component 

Unfortunately, I [haven't managed](https://github.com/jupyter-widgets/ipywidgets/issues/1824) to tinker with your web3 example, yet.

I do agree that monkey patching the CSS is not very elegant. On the other hand it makes Appmode pretty lightweight (<300LoC) and the classic notebook seems to be fairly stable. Then again, I would also like to add JupyterLab support and I suppose the output component would be the way to go, right? 

> but the 'app mode' is confined to specially-marked cells.

What use cases do you have in mind for this? Comments and debugging stuff can already be hidden in code cells. Generally, I'd be afraid that this causes confusion among users because metadata is pretty invisible to them. Hence, I would like to keep the current behavior as a default in any case.

**Comment by oschuett** [comment]
Dear @jasongrout,

I've been thinking a bit more about how to move forward on your proposal...

AFAIK, the `@jupyterlab/services` are not available in the classic notebook. Hence, for those users I'll have to keep the currently implementation of Appmode, right?

However, I would also like to see Appmode in JupyterLab. Again, I find it very important that users can easily switch between the two views. Therefore, I did a bit of reading on [notebook extensions](https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook-extension/). Unfortunately, it's not clear to me how I could implement Appmode within that framework. Maybe you could give me some hints?

**Comment by jasongrout** [comment]
First, I think what you've done is great, and fills a need in the community - thanks again!

Second, I think maybe I wasn't clear enough in my explanation. What I'm proposing is an entirely new (but simple) webapp, served from a new server extension, based on the ipywidgets web3 example, which doesn't use the classic notebook javascript code at all, and also is not an extension in jupyterlab. Basically, take the current web3 example, and add something which fetches a given notebook, parses it for code cells, executes the code, and displays the results.

I'll try to find some time soon-ish to experiment with actually coding something, rather than just talking about it - or I'm happy to discuss if someone else wants to experiment with coding it up.

**Comment by jasongrout** [comment]
Here is a WIP PR to ipywidgets implementing the start of what I was thinking: https://github.com/jupyter-widgets/ipywidgets/pull/1862

**Comment by oschuett** [comment]
I'm going to close this issue. I think, for the time being Appmode is filling a niche. In the meantime the greater discussion about _dashboarding_ continues [here](https://github.com/jupyter-widgets/ipywidgets/issues/2018). Thanks @jasongrout for driving this forward!

**Comment by jasongrout** [comment]
Sounds good. I'm also pursuing this idea as I have time.
