### ISSUE TITLE
Javascript code does not work with AppMode

### ISSUE THREAD

**Issue by soerendip** [oschuett/appmode#37]
Hi, 
I need to assign the port of the notebook server to a variable and make a function call with it to get Bokeh to work. The code below works in the normal notebook setting, but when I run it with AppMode the variable PORT is not assigned a value and the code breaks. Any idea why it is not working and how to work around it?

```
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {return false;}
var nb = Jupyter.notebook;
var port = window.location.port;
nb.kernel.execute("PORT = '" + port + "'");
```

Great app, by the way!!

**Comment by oschuett** [comment]
The problem is that your assignment statement is executed after all cells have run. This is because Appmode queues the execution of all cells at once. Hence, when your javascript cell is executed the assignment is added to the end of the queue.

A simple solution would be to parse the `jupyter_notebook_url` which is injected by Appmode:
```
from urllib.parse import urlparse
PORT = urlparse(jupyter_notebook_url).port
```
Note, that port is empty if it's not explicitly contained in your url.
