### ISSUE TITLE
Appmode temp files

### ISSUE THREAD

**Issue by shyam334** [oschuett/appmode#38]
Hello,

I'm running appmode 0.5.0 in jupyterhub, and I have some questions. 

- Is there a way to specify the temp directory for app mode. (where the temp notebooks and checkpoints are created)

  As expected, appmode fails if I don't have write permissions in the directory and checkpoint dir, where the notebook resides.
  Is there a way to execute read-only notebooks in a read-only directory.

- How do you (/what) trigger the cleanup of the temporary notebooks created by appmode
  In my case, temp notebooks, and checkpoints aren't cleaned up.

  My usage pattern is, I directly access the appmode app via url and close the browser page, once I'm done.

Thanks for Appmode, its quite useful.

**Comment by oschuett** [comment]
Sorry for the late reply.

> Is there a way to specify the temp directory for app mode.

Not at the moment and I'm not not sure it would actually be helpful. Many notebooks depend on other files being in the same directory. To be on the save side one would have to recursively copy the entire directory, which does not seem practical. Nevertheless, if you manage to come up with something or need a hook for your custom solution, feel free to send a PR.

> How do you (/what) trigger the cleanup of the temporary notebooks created by appmode

The cleanup is triggered via [window.onbeforeunload](https://github.com/oschuett/appmode/blob/master/appmode/static/main.js#L126). This is indeed not very reliable because browsers are hesitant to execute javascript after the user left the page.

**Comment by vhorvath** [comment]
My temp files are not being removed either in two independent installations (the folders/files are not read only). It would be great to log when there is a condition that prevents removal from happening. My log files are devoid of anything useful. It seems that the `delete()` method of the `AppmodeHandler` class is not being called at all. I am now suspecting that the `@web.authenticated` might be in the way of doing so for me, but I am not quite sure.

Do you have any suggestion how to go about testing this hypothesis? - I have no problem switching to Appmode which has the same decorator... So there may be something else at play.

**Comment by oschuett** [comment]
My guess would be that the http request is never issued by the browser. You can check this in the web-developer console. This relies on [window.onbeforeunload](https://github.com/oschuett/appmode/blob/master/appmode/static/main.js#L126), which is unfortunately not very reliable.
