### ISSUE TITLE
HTTP 400 : Bad Request

### ISSUE THREAD

**Issue by MJKnowling** [oschuett/appmode#64]
@oschuett 

When I launch the "Try it live" AppMode example and I receive the error:

400 : Bad Request

The error was: Cannot create file or directory '/home/jovyan/... .ipynb'

The reason for trying this is because my MyBinder repos are also now returning the same error when launching AppMode. 

Is there a new dependency that you are aware of? 

Any ideas/suggestions would be much appreciated!

**Comment by yakeeliuliu** [comment]
Hi, I am running into the same issue now.

**Comment by erobiquee** [comment]
It seems that for some reason jupyter notebook does not have permission to write hidden files anymore. As a workaround you can start the notebook with ```--ContentsManager.allow_hidden=True``` or set that in the config file. However, this will also show hidden files in the file browser which is a bit annoying.

**Comment by fomightez** [comment]
To follow on erobiquee's excellent advice for a workaround, you can find an example config file [here](https://github.com/fomightez/simple_appmode_binder/blob/main/jupyter_notebook_config.py) that allows appmode to work in mybinder again. 

The showing the hidden files isn't too much of an issue if you are working in the appmode mode. My example didn't involve interacting with files in the session and so maybe that aspect is messier than usual.

**Comment by olivertlord** [comment]
Hi, I have tried @fomightez's workaround but I think it is broken again. The luunch [here](https://mybinder.org/v2/gh/fomightez/test_json_appmode/9a1d16ec3953269e17a3d58d2b9ea579157f8aaa?urlpath=apps%2Findex.ipynb) now returns "500 : Internal Server Error".

I have a [repo](https://github.com/olivertlord/hydrous-melts) that used to launch into appmode using [this url](https://mybinder.org/v2/gh/olivertlord/hydrous-melts/main?urlpath=apps/hydrous_melt_PVTX.ipynb), but now I get "404 : Not Found You are requesting a page that does not exist!"

Any suggestions would be greatly appreciated!

**Comment by fomightez** [comment]
Yes, sorry @olivertlord . [MyBinder announced a sort of big update like a week after](https://discourse.jupyter.org/t/mybinder-org-and-repo2docker-updates/18333?u=fomightez) I got the workaround working and I think changing the default server broke it. That's my guess anyways. It was definitely working well with the workaround just a few days before that. 

Based on [here](https://discourse.jupyter.org/t/streamlit-500-internal-server-error/5995/14?u=fomightez), I'm wondering if going over into an available terminal by using the URL to switch over to either the JupyterLab or classic interface and running `less ~/.jupyter-server-log.txt` would shed any light. I think that would be a good place to start before posting at the Jupyter Community Discourse forum since they do say to let them know if we encounter issues. [Last time I thought it was that](https://discourse.jupyter.org/t/streamlit-500-internal-server-error/5995/13?u=fomightez), it turned out not to be and so I'm a little hesitant to pinpoint this as the issue; however, it did seem to coincide.

**Comment by fomightez** [comment]
Had that run included trying to open in the appmode mode? 

It may be enough to just tag the post announcing MyBinder switching the server over with a link [to your post above](https://github.com/oschuett/appmode/issues/64#issuecomment-1470882016) and saying Appmode had been working via launches from MyBinder after a setting the config to show hidden files. And then it broke again around the time of this announcement. Then say see this thread for more details.

**Comment by olivertlord** [comment]
Sorry - now I understand. The log does not include me attempting to launch in appmode. I will create a new one, and then I will tag the announcement and try and explain things. Thanks for your help.

**Comment by fomightez** [comment]
See reply [here](https://discourse.jupyter.org/t/mybinder-org-and-repo2docker-updates/18333/3?u=fomightez) and the note over at [binder-examples/appmode needs workaround to enable appmode to work for now #275](https://github.com/jupyterhub/mybinder.org-user-guide/issues/275). Promising.

**Comment by olivertlord** [comment]
Yes, I saw that. Thanks for pointing me in the right direction!

**Comment by PabloPiaggi** [comment]
Have you found a solution for this problem? I noticed that the “Try it live” binder launcher is still failing with the above-mentioned error. I have an application that depends on Appmode and this is an important issue for me. When you find a solution, please update the example, so I can update my repository as well. Thank you.

**Comment by oschuett** [comment]
Fixed in [release v0.9.0](https://github.com/oschuett/appmode/releases/tag/v0.9.0).

**Comment by oschuett** [comment]
Yeah, I'm very sorry for the long silence. I hope this resolved the issue. I also tried testing with mybinder, but they seem overloaded at the moment.

**Comment by olivertlord** [comment]
@oschuett Presumably related to this: https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f
